version: '3'

# Docker's internal networking lets each service can be addressed
# by its service name as a URL eg conductor-service-phr:8000
services:
  conductor-service-phr:
    image: rtweed/qewd-server
    volumes:
      - /ripple-qewd/conductor-service-phr:/opt/qewd/mapped
      - /ripple-qewd/conductor-service-phr/www:/opt/qewd/www
    ports:
      - "8000:8080"

  openid-connect-server:
    image: rtweed/qewd-server
    volumes:
      - /ripple-qewd/openid-connect-server:/opt/qewd/mapped
    ports:
      - "8080:8080"

  # master patient index service
  # enables demographic lookup and identification of ehrId for a patient
  mpi-service:
    image: rtweed/qewd-server
    volumes:
      - /ripple-qewd/mpi-service:/opt/qewd/mapped
    ports:
      - "8002:8080"

  authentication-service-phr:
    image: rtweed/qewd-server
    volumes:
      - /ripple-qewd/authentication-service-phr:/opt/qewd/mapped
      - /ripple-qewd/yottadb/authentication:/root/.yottadb/r1.22_x86_64/g
    ports:
      - "8001:8080"

  # contains clinical data, requires an ehrId from the MPI service
  cdr-service-openehr:
    image: rtweed/qewd-server
    volumes:
      - /ripple-qewd/cdr-service-openehr:/opt/qewd/mapped
      - /ripple-qewd/yottadb/openehr:/root/.yottadb/r1.22_x86_64/g
    ports:
      - "8003:8080"
